default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  pool: 5

development:
  <<: *default
  database: dos_opportunities_development

test: &test
  <<: *default
  database: dos_opportunities_test

production:
  <<: *default
  database: dos_opportunities_production

